#!/usr/bin/env python

from gordon import *
from gi.repository import Gtk, Gdk

class MainWin(Gtk.Window):
	def destroy(self, *_):
		Gtk.Window.destroy(self)
		if self.in_main:
			Gtk.main_quit()
			self.in_main = False

	def main(self):
		self.in_main = True
		Gtk.main()

	def kb_space(self, *_):
		w = self.stack.get_visible_child()
		w.kb_space()

	def __init__(self, nouns):
		Gtk.Window.__init__(self)
		self.in_main = False
		self.connect('destroy', self.destroy)
		self.set_default_size(320, 280)

		hb = Gtk.HeaderBar()
		hb.set_show_close_button(True)
		hb.props.title = 'Korean vocabulary'
		self.set_titlebar(hb)

		vb = Gtk.Box(orientation = Gtk.Orientation.VERTICAL,
				spacing = 6)
		self.add(vb)

		accel = Gtk.AccelGroup()
		accel.connect(Gdk.keyval_from_name('Q'),
				Gdk.ModifierType.CONTROL_MASK,
				0,
				self.destroy)
		self.add_accel_group(accel)

		accel = Gtk.AccelGroup()
		accel.connect(Gdk.keyval_from_name('W'),
				Gdk.ModifierType.CONTROL_MASK,
				0,
				self.destroy)
		self.add_accel_group(accel)

		accel = Gtk.AccelGroup()
		accel.connect(Gdk.keyval_from_name('Escape'),
				0,
				0,
				self.destroy)
		self.add_accel_group(accel)

		accel = Gtk.AccelGroup()
		accel.connect(Gdk.keyval_from_name('space'),
				0,
				0,
				self.kb_space)
		self.add_accel_group(accel)

		self.stack = Gtk.Stack()
		self.stack.set_transition_type(\
				Gtk.StackTransitionType.SLIDE_LEFT_RIGHT)
		self.stack.set_transition_duration(500)

		c = LearnUI(nouns)
		self.stack.add_titled(c, 'learn', 'Learn')
		self.stack.child_set_property(c, 'icon-name',
					'accessories-dictionary-symbolic')

		c = LearnUI(nouns)
		self.stack.add_titled(c, 'test', 'Test')
		self.stack.child_set_property(c, 'icon-name',
				'application-certificate-symbolic')

		stack_switcher = Gtk.StackSwitcher()
		stack_switcher.set_stack(self.stack)

		hb.pack_end(stack_switcher)
		vb.pack_start(self.stack, True, True, 0)

		self.show_all()

if __name__ == '__main__':
	words = load_from_csv('data/nouns.csv')
	x = MainWin(words)
	x.main()
